### ISSUE TITLE
no such property docker for class dockerUitls

### ISSUE THREAD

**Issue by liupeng0518** [massimo1993/jenkins-docker-library#1]
run this library:
```
no such property: docker for class dockerUitls
```

**Comment by massimo1993** [comment]
@liupeng0518 Can you share your Jenkinsfile so I can see how you are using the library?

**Comment by massimo1993** [comment]
@liupeng0518 Did you install Docker Pipeline plugin in Jenkins? The library requires that you install the plugin in order to use Docker.

https://plugins.jenkins.io/docker-workflow/

**Comment by liupeng0518** [comment]
Now It is OK，thank you.
